### ISSUE TITLE
Unable to compile on  ESPHome 2025.2.0

### ISSUE THREAD

**Issue by ipjcrane** [glmnet/esphome-components#7]
Thank you for your excellent work. In the recent update to ESPHome  2025.2.0 custom components are not longer supported. So I am trying to migrate my code to this external component.

I have made the most basic of YAML config.

```
.... usual ESPHome config stuff.....

external_components:
  source: github://glmnet/esphome-components
  components: [arduino_port_expander]

arduino_port_expander:
  id: ape1 
  address: 0x08
  analog_reference: DEFAULT

sensor:
  - platform: arduino_port_expander
    id: sx
    pin: A0
    name: Ardu A0
    update_interval: 10s
```
but when I add a binary_sensor:
```
binary_sensor:
  - platform: gpio
    pin:
      arduino_port_expander: ape1
      number: 1
      mode:
        input: true # defaults to False
    id: Test1
```

I get the error

```
src/main.cpp: In function 'void setup()':
src/main.cpp:277:111: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
  277 |   arduino_port_expander_arduinoportexpandergpiopin_id = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
      |                                                                                                               ^
In file included from src/esphome.h:15,
                 from src/main.cpp:3:
src/esphome/components/arduino_port_expander/arduino_port_expander.h:56:7: note:   because the following virtual functions are pure within 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin':
   56 | class ArduinoPortExpanderGPIOPin : public GPIOPin {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:9,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/gpio.h:61:23: note:     'virtual esphome::gpio::Flags esphome::GPIOPin::get_flags() const'
   61 |   virtual gpio::Flags get_flags() const = 0;
      |                       ^~~~~~~~~
*** [.pioenvs/test/src/main.cpp.o] Error 1
```

What am I doing wrong? any help would be much appreciated.

**Comment by ipjcrane** [comment]
I can confirm I can compile the code on ESPHome 2024.12 but not on 2025.2

**Comment by ipjcrane** [comment]
It seems there is a fixed version that compiles in ESPHome 2025.2.0 which can be found here https://github.com/mbohdal/esphome-components
